name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout Mongo
        uses: actions/checkout@v2
        with:
          path: vlib/mongo
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libglfw3-dev libxi-dev libxcursor-dev
      - name: Build V
        run: |
          make
          sudo ./v symlink
      - name: Test
        run: |
          cd ./vlib/mongo/
          v test .
      - name: Build Mongo shared lib
        run: |
          cd ./vlib/mongo/
          v -shared .
      - name: Build Mongo example
        run: |
          cd ./vlib/mongo/examples/
          v -prod example.v